import Head from "next/head";
import Layout from "../../components/layout";
import Link from "next/link";


export default function index({ data }) {
  return (
    <Layout>
      <>
        <Head>
          <title>Lista de Posts | Next.js</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <h1>Lista de artículos</h1>
        {data.map(({ id, title, body }) => (
          <div key={id}>
            <h3>
              <Link legacyBehavior href={`/blog/${id}`}>
              <a>{id} - {title}</a>
              </Link>
            </h3>
            <p>{body}</p>
          </div>
        ))}
      </>
    </Layout>
  )
}

export async function getStaticProps() {
  try {
    const res = await fetch("https://jsonplaceholder.typicode.com/posts");
    const data = await res.json();
    return {
      props: {
        data, //lo mismo que colocar -> data: data
      },
    };
  } catch (error) {
    console.log(error);
  }
}